 CREATE TABLE IF NOT EXISTS presale_inventory_unit (
   ID varchar(100) NOT NULL,
   STAMP_DEFINITION_ID varchar(100) NOT NULL unique,
   INVENTORY_LEVEL int DEFAULT NULL,
   INIT_INVENTORY_LEVEL int,
   CREATE_DATE timestamp NOT NULL,
   UPDATE_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预售劵库存信息';

 CREATE TABLE IF NOT EXISTS presale_stamp_definition_product_binding (
   ID varchar(100) NOT NULL,
   STAMP_DEFINITION_ID varchar(100) NOT NULL unique,
   CATEGORY_ID varchar(100) DEFAULT NULL,
   SUB_CATEGORY_ID varchar(100) DEFAULT NULL,
   PRODUCT_ID varchar(100) DEFAULT NULL,
   EFFECT_DATE timestamp,
   EXPIRY_DATE timestamp,
   CREATE_DATE timestamp NOT NULL,
   UPDATE_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   MANAGER_ID VARCHAR(45) NULL,
   MANAGER_NAME VARCHAR(45) NULL,
   BU_CODE VARCHAR(45) NULL,
   PRODUCT_NAME VARCHAR(300),
   DEPART_ID varchar(45) DEFAULT NULL,
   PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预售劵绑定产品信息';

 CREATE TABLE IF NOT EXISTS stamp (
   ID varchar(100) NOT NULL,
   STAMP_DEFINITION_ID varchar(100) NOT NULL,
   NAME varchar(64) NOT NULL,
   SERIAL_NUMBER varchar(64) NOT NULL,
   ORDER_ID varchar(64) NOT NULL,
   USE_ORDER_ID varchar(64) DEFAULT NULL,
   USE_ORDER_ITEM_ID varchar(64) DEFAULT NULL,
   USE_ORDER_CATEGORY_ID varchar(20) DEFAULT NULL,
   REFUND_ORDER_ID varchar(64),
   CUSTOMER_ID varchar(100) NOT NULL,
   STAMP_STATUS varchar(100) NOT NULL,
   PRICE INT,
   EXPIRED_DATE TIMESTAMP DEFAULT '0000-00-00 00:00:00',
   CREATE_DATE timestamp NOT NULL,
   UPDATE_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='劵码';

 CREATE TABLE IF NOT EXISTS stamp_definition (
   ID varchar(100) NOT NULL,
   STAMP_NO VARCHAR(10) NULL,
   NAME varchar(64) NOT NULL,
   PRINT_PRICE decimal(10,2) DEFAULT NULL,
   SALE_PRICE decimal(10,2) DEFAULT NULL,
   SET_PRICE decimal(10,2) DEFAULT NULL,
   DOWN_PAYMENT decimal(10,2) DEFAULT NULL,
   REMARKS varchar(4000) DEFAULT NULL,
   REMIND_CUSTOMER_DATE timestamp,
   STAMP_ONSALE_START_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
   STAMP_ONSALE_END_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
   STAMP_REDEEMABLE_START_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
   STAMP_REDEEMABLE_END_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
   BALANCE_DUE_IN_HOUR int DEFAULT NULL,
   ASSOCIATED_PROD_AVAIL_TIMESLOT varchar(4000) DEFAULT NULL,
   ACTIVITY_STATUS varchar(100) NOT NULL,
   BUY_MAX int DEFAULT '0',
   PRODUCT_MANAGER_ID varchar(100) DEFAULT NULL,
   RULE_RESTRICT varchar(4000) DEFAULT NULL,
   DESCRIPTION varchar(400) DEFAULT NULL,
   CREATE_DATE timestamp NOT NULL,
   UPDATE_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='劵信息及定义';
 
 CREATE TABLE IF NOT EXISTS presale_stamp_definition_product_relation (
   ID varchar(100) NOT NULL,
   STAMP_DEFINITION_ID varchar(100) NOT NULL unique,
   CATEGORY_ID varchar(100) DEFAULT NULL,
   PRODUCT_ID varchar(100) DEFAULT NULL,
   PRODUCT_BRANCH_ID varchar(100) DEFAULT NULL,
   GOODS_ID varchar(100) DEFAULT NULL,
   CREATE_DATE timestamp NOT NULL,
   UPDATE_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预售劵虚拟产品规格商品关联表';
 
 CREATE TABLE IF NOT EXISTS presale_stamp_definition_goods_binding (
	ID varchar(100) NOT NULL,
  STAMP_DEFINITION_ID varchar(100) NOT NULL,
  GOODS_ID varchar(100) DEFAULT NULL,
  GOODS_NAME varchar(45) DEFAULT NULL,
  BRANCH_FLAG varchar(45) DEFAULT NULL,
  CATEGORY_ID VARCHAR(20) DEFAULT NULL,
  CREATE_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  UPDATE_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预售劵绑定商品信息';
 
 
 CREATE TABLE IF NOT EXISTS stamp_refund_order (
  ID varchar(64) NOT NULL,
  REFUND_APPLY_ID varchar(64),
  REFUND_ID varchar(64),
  ORDER_ID varchar(64),
  USER_ID varchar(64),
  REFUND_NUM int,
  STAMP_AMOUNT int,
  REFUND_AMOUNT int,
  REFUND_STATUS varchar(20),
  CREATE_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  UPDATE_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预售劵退款单';
 
 CREATE TABLE IF NOT EXISTS stamp_operate_log (
  ID varchar(64) NOT NULL,
  OPERATE_TYPE varchar(20) NOT NULL,
  OBJECT_ID varchar(64),
  STAMP_CODE varchar(64),
  REMARK varchar(400),
  CREATE_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='券码操作日志';

 CREATE TABLE IF NOT EXISTS stamp_unbind_order (
  ID varchar(64) NOT NULL,
  REFUND_ID varchar(64),
  USE_ORDER_ID varchar(64),
  USE_ORDER_ITEM_ID varchar(64),
  STAMP_CODE varchar(64),
  CREATE_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预售劵解绑';
 
 
 CREATE INDEX idx_stamp_order ON STAMP (ORDER_ID);
 CREATE INDEX idx_stamp_use_order ON STAMP (USE_ORDER_ID);
 CREATE INDEX idx_stamp_use_customer ON STAMP (CUSTOMER_ID);
 CREATE INDEX idx_stamp_refund ON STAMP (REFUND_ORDER_ID);

 CREATE INDEX idx_stamp_refund_order_apply ON stamp_refund_order (REFUND_APPLY_ID);
 CREATE INDEX idx_stamp_refund_order_refund ON stamp_refund_order (REFUND_ID);
 CREATE INDEX idx_stamp_refund_order_order ON stamp_refund_order (ORDER_ID);
 
 
 CREATE TABLE IF NOT EXISTS down_grade_method (
  ID varchar(64) NOT NULL,
  APP_NAME varchar(100) NOT NULL,
  METHOD_NAME varchar(256),
  DISABLED varchar(1),
  UPDATE_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CREATE_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预售劵解绑';
 