 
 CREATE TABLE IF NOT EXISTS down_grade_method (
  ID varchar(64) NOT NULL,
  APP_NAME varchar(100) NOT NULL,
  METHOD_NAME varchar(256),
  DISABLED varchar(1),
  UPDATE_DATE timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CREATE_DATE timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (ID)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预售劵解绑';
 
 
 ALTER TABLE stamp_definition ADD  OPERATIONS_AMOUNT decimal(16,2)  DEFAULT NULL  AFTER SET_PRICE;