 ALTER TABLE `stamp_definition` 
        ADD COLUMN STAMP_REDEEMABLEL_TIMESLOT VARCHAR (4000), 
        ADD COLUMN REMIND_CUSTOMER_TIMESLOT VARCHAR (4000),
        ADD COLUMN STAMP_ORDER INT(2) DEFAULT 1;
        
        
        