spring:
  profiles:
    active: ${PROFILE:local}
    default: ${PROFILE:local}

  #spring data source
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        globally_quoted_identifiers: true
    show-sql: true
    
  # following are the settings for master DB, 
  # slave setting is inside db.mysql-slave.properties
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://10.200.3.178/hhs}
    username: ${MYSQL_USER:hhs}
    password: ${MYSQL_PASS:123456}
    driver-class-name: com.mysql.jdbc.Driver
    test-while-idle: true
    time-between-eviction-runs-millis: 30000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1
    remove-abandoned: true
    remove-abandoned-timeout: 60
    
  # cache service
  redis:
    database: ${REDIS_DB_NUM:0}
    host: ${REDIS_URL:192.168.0.81}
    port: ${REDIS_PORT:6379}
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1
      
  cloud:
    config:
      enabled: false

server:
  port: ${SERVER_PORT:8181}

# ignore flyway validation
flyway:
  validateOnMigrate: false
  baselineOnMigrate: true
# setting for eurake server registry
# HOST_NAME is the hostname in current machine
eureka:
  instance:
    hostname: ${HOST_NAME:localhost}
  client:
    enabled: true
    serviceUrl:
      defaultZone:  http://${EURAKE_URL:127.0.0.1}:8761/eureka/